### PR TITLE
Changes to fix options binding in .Net 7.0.1

### PR DESCRIPTION
**Pull request by V1RuSyRa**
There are some changes were made in .Net 7.0.1 to options with collections binding process and this fix is need to properly handle it.

### CODE REVIEW

**Comment by msmolka** [comment]
I'm trying to find any issue with .net7 but cannot. I've updated projected to .net 7 and all tests are passing. Could you provide test case (e.g. add unit test) when this will fail?

**Comment by msmolka** [comment]
I've pushed new changes with .net 7. And no issue with tests

**Comment by V1RuSyRa** [comment]
It fails on 2 of tests that you already have. 
image

What version of SDK do you use? 7.0.100 or 7.0.101? On version 7.0.100 there are no problems, but on version 7.0.101 there are.

**Comment by msmolka** [comment]
Ok, this is strange in 7.0.0 and below it works. I believe it is bug in 7.0.1 and will raise it on .net hub. I will approve these changes as workaround

**Comment by andyTheCoder** [comment]
Hi, any chance of creating a new nuget package containing this fix ?

**Comment by msmolka** [comment]
Hi, I've stopped releasing this, because this is bug in .NET Core 7.0.1 and 7.0.2 and already fixed in version 7.0.3
https://github.com/dotnet/runtime/pull/80562
https://github.com/dotnet/runtime/issues/79904

But maybe it would be good to do this.
Will try soon. 

The bug is in Microsoft.Extensions.Configuration.Binder package
use version 7.0.0 or 7.0.3 and above

**Comment by msmolka** [comment]
Any way... I've pushed new nuget. Sorry for delay. I was hoping that .net core fix would be released earlier

**Comment by andyTheCoder** [comment]
Thank you very much for your swift response. :beers:

**Pull request merged**
